/* Generated By:JavaCC: Do not edit this line. MyNewGrammarConstants.java */
package com.sjsu.crawler.parsergrammar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int STARTTEXT = 2;
  /** RegularExpression Id. */
  int STRING = 3;
  /** RegularExpression Id. */
  int nested_STARTTEXT = 10;
  /** RegularExpression Id. */
  int ENDTEXT = 11;
  /** RegularExpression Id. */
  int OTHERTAGS = 12;
  /** RegularExpression Id. */
  int TEXT = 13;
  /** RegularExpression Id. */
  int UNICODE_TEXT = 14;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int REQUIRED_TEXT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<STARTTEXT>",
    "<STRING>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\f\"",
    "<nested_STARTTEXT>",
    "<ENDTEXT>",
    "<OTHERTAGS>",
    "<TEXT>",
    "<UNICODE_TEXT>",
  };

}
